"""Event type vocabulary (spec §11). The event log is the system of record."""

from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    SCENARIO_STARTED = "SCENARIO_STARTED"
    LAB_PROVISIONED = "LAB_PROVISIONED"
    FAULT_APPLIED = "FAULT_APPLIED"
    FAULT_REVERTED = "FAULT_REVERTED"
    TICKET_OPENED = "TICKET_OPENED"
    CHAT_MESSAGE_SENT = "CHAT_MESSAGE_SENT"
    CHAT_MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED"
    WIKI_PAGE_VIEWED = "WIKI_PAGE_VIEWED"
    CHANGE_LOG_VIEWED = "CHANGE_LOG_VIEWED"
    MONITORING_VIEWED = "MONITORING_VIEWED"
    DEVICE_CONNECTED = "DEVICE_CONNECTED"
    COMMAND_EXECUTED = "COMMAND_EXECUTED"
    CONFIG_CHANGED = "CONFIG_CHANGED"
    SERVICE_FAILED = "SERVICE_FAILED"
    NETWORK_CONNECTIVITY_LOST = "NETWORK_CONNECTIVITY_LOST"
    NETWORK_CONNECTIVITY_RESTORED = "NETWORK_CONNECTIVITY_RESTORED"
    PROBER_STARTED = "PROBER_STARTED"
    PROBER_STOPPED = "PROBER_STOPPED"
    VERIFICATION_RUN = "VERIFICATION_RUN"
    VERIFICATION_PASSED = "VERIFICATION_PASSED"
    INCIDENT_UPDATED = "INCIDENT_UPDATED"
    ESCALATION_REQUESTED = "ESCALATION_REQUESTED"
    POSTMORTEM_SUBMITTED = "POSTMORTEM_SUBMITTED"
    SCENARIO_COMPLETED = "SCENARIO_COMPLETED"
    LAB_DESTROYED = "LAB_DESTROYED"
    SESSION_TIMED_OUT = "SESSION_TIMED_OUT"
    SESSION_IDLE_EXPIRED = "SESSION_IDLE_EXPIRED"


# Read-only commands used for the evidence-before-change ratio (spec §22).
READ_COMMAND_PREFIXES = ("show", "ping", "traceroute", "display", "cat", "ip ", "ss ", "netstat")
CONFIG_COMMAND_MARKERS = ("configure terminal", "conf t", "configure")
