frr defaults traditional
hostname AUS-RTR1
service integrated-vtysh-config
!
interface eth1
 description WAN transit to HQ-RTR1
 ip address 10.255.0.2/30
exit
!
interface eth2
 description Austin user subnet (via AUS-SW1)
 ip address 10.20.10.1/24
exit
!
router ospf
 ospf router-id 10.0.0.2
 network 10.255.0.0/30 area 0
 network 10.20.10.0/24 area 0
exit
!
end
