frr defaults traditional
hostname HQ-RTR1
service integrated-vtysh-config
!
interface eth1
 description HQ application subnet
 ip address 10.10.10.1/24
exit
!
interface eth2
 description HQ user subnet
 ip address 10.10.20.1/24
exit
!
interface eth3
 description WAN transit to AUS-RTR1 (Austin)
 ip address 10.255.0.1/30
exit
!
interface eth4
 description NetOps monitoring probe
 ip address 10.10.30.1/30
exit
!
router ospf
 ospf router-id 10.0.0.1
 network 10.10.10.0/24 area 0
 network 10.10.20.0/24 area 0
 network 10.10.30.0/30 area 0
 network 10.255.0.0/30 area 0
exit
!
access-list MGMT-SSH seq 10 permit 10.10.20.0/24
access-list MGMT-SSH seq 20 deny any
!
end
